<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Parking_Parking</name>
   <tag></tag>
   <elementGuidId>12f4292b-ea3f-44ca-adea-f788ffb67b2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Parking</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Parking']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>041d3e98-e9f3-4d5b-b5d2-5ab7deb652e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Parking</value>
      <webElementGuid>bcdbf87d-5567-4be6-bd27-1df35dc8e047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Parking</value>
      <webElementGuid>b125e768-0999-4412-a242-09737161d755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d9d07c41-847c-4a3a-96a2-2422faea9f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a719e6a4-b3b0-4b5d-9f77-64c5e566e105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Parking</value>
      <webElementGuid>91885c25-5363-49e0-829a-8f4c29cae298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Parking&quot;)</value>
      <webElementGuid>29b4834b-17e8-4a44-aa63-d49191fe4dd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Parking']</value>
      <webElementGuid>da5dfec8-e573-4911-b864-5efb76b99127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[27]/div[4]/div/label/input</value>
      <webElementGuid>432c1b10-5196-4147-9f77-5a3e5dac7dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/label/input</value>
      <webElementGuid>65903f98-def0-45b0-9271-1b305f5805c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Parking' and @name = 'Parking' and @type = 'checkbox']</value>
      <webElementGuid>7e9cb62d-e58d-4730-98b7-e9f8da3e8d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
