<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Jacuzzi_Jacuzzi</name>
   <tag></tag>
   <elementGuidId>8d001127-6efe-4c80-9873-babfd05dbff2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Jacuzzi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Jacuzzi']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c464de48-b95b-4c86-88b7-76d19c9c7f7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Jacuzzi</value>
      <webElementGuid>454e2fd0-0c99-4173-94c6-70f825e72ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Jacuzzi</value>
      <webElementGuid>2b86fd0b-a672-4d46-ad68-c3597530014b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>51878505-7abf-4224-bfca-0e0031fde2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>505d2562-4655-4382-bb5c-adec87377a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Jacuzzi</value>
      <webElementGuid>acf4b5f9-cbd3-458a-b0e6-c626221814fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Jacuzzi&quot;)</value>
      <webElementGuid>ef2dffe4-c2f5-47d2-96f0-f2d454caef39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Jacuzzi']</value>
      <webElementGuid>1f896c66-3849-47cc-985b-802a061c4963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[27]/div[6]/div/label/input</value>
      <webElementGuid>e11d04dc-8e7b-4a96-9ade-b45babf3ebfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/label/input</value>
      <webElementGuid>d4b5386d-46cf-4d7c-b2bc-db5e234bd0f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Jacuzzi' and @name = 'Jacuzzi' and @type = 'checkbox']</value>
      <webElementGuid>a02b5a4d-6d6c-4a28-b846-f77e70877181</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
