<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_New(Developer Unit)_Property Listing</name>
   <tag></tag>
   <elementGuidId>fd311a4b-a241-4cc5-98be-44f2cb8d3116</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Projects</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Projects']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ec42b54-468b-4073-a758-a5e1ca326d3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Projects</value>
      <webElementGuid>1ba572c6-f922-4a01-a12c-3f18cd0c4739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Property Listing</value>
      <webElementGuid>ee43517e-7289-473b-9418-aa24b0977333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d2487048-eb50-43f6-8ed2-4dd4a10e0dcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1676318f-5394-4c97-a96c-0b32ccc64939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Projects</value>
      <webElementGuid>43f2d798-669a-4ee1-8cb2-8b46380a5294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Projects&quot;)</value>
      <webElementGuid>d2add6d7-a084-4ef2-a0b1-358fd11ed451</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Projects']</value>
      <webElementGuid>f2df060d-03f7-48f2-94ac-d21b2dc9435d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[3]/div[2]/div/label/input</value>
      <webElementGuid>dd6d771d-b5f3-453c-aadb-2733dc940c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/label/input</value>
      <webElementGuid>f8d6126d-e2f6-4e9e-b9c1-d6bfc4e833ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Projects' and @name = 'Property Listing' and @type = 'radio']</value>
      <webElementGuid>90464c24-8309-4818-9d46-e0b7134ae621</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
