<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_BBQ_BBQ</name>
   <tag></tag>
   <elementGuidId>1b76f0e3-0d4b-4860-9957-5e070f1210a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BBQ</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BBQ']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b1356050-3432-46a6-8b93-f71f1682b686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BBQ</value>
      <webElementGuid>408abfd7-9286-46c5-8ffd-0a8d79bd3576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BBQ</value>
      <webElementGuid>b8dba258-7cac-4bba-817f-59d364c78c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cab9ec30-1769-4ad6-ac9f-ab875a234dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>c28f7646-9ca3-4012-852e-d57b8b48f7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>BBQ</value>
      <webElementGuid>e89f27df-dc35-4a1b-8496-5c988513a964</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BBQ&quot;)</value>
      <webElementGuid>0fc869a3-3a26-4b3c-91a6-bce278d5103f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BBQ']</value>
      <webElementGuid>713862c4-9451-4bbc-b87a-205596611dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[27]/div/div/label/input</value>
      <webElementGuid>4cc82302-838b-43b1-926f-93cde7207582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[27]/div/div/label/input</value>
      <webElementGuid>19f0a3a6-fb5d-4da7-bd0f-b1049708ca13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BBQ' and @name = 'BBQ' and @type = 'checkbox']</value>
      <webElementGuid>1bc729df-ce25-4304-9c85-d1f8ae1ef4ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
