<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commercial_Listing Category</name>
   <tag></tag>
   <elementGuidId>f5738ba0-cb1c-43a3-a5c7-cce84cb97a66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Commercial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Commercial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5ebfeaf0-c004-473e-8b6f-cc17a5e33c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>48792e14-80a4-4486-8b93-bb9ab72b58d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Listing Category</value>
      <webElementGuid>af8cfdd5-8d4b-4204-9afa-0084fd48a5c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>78ce32d0-7806-4069-8e0c-8a87fbbdaf7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>de3e55c4-3b8f-4dbb-b304-c5dd102261e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>1de1cf67-3bc0-475d-aca4-bf0966e0c9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Commercial&quot;)</value>
      <webElementGuid>51e7920f-6a53-4f34-b018-de08f0623969</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Commercial']</value>
      <webElementGuid>3372b25e-98d1-4243-b1c8-a450f5458c2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[5]/div/div/label/input</value>
      <webElementGuid>340cfa80-d83f-4f23-b214-be3fd4afc461</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label/input</value>
      <webElementGuid>0909e26a-1c48-489f-80a1-e7a133af7eac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Commercial' and @name = 'Listing Category' and @type = 'radio']</value>
      <webElementGuid>26474806-6b70-498a-972b-88a574b7a917</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
