<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sale_Property For</name>
   <tag></tag>
   <elementGuidId>69b7a5da-f45d-4dc4-ada2-76f7aa409111</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Buy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Buy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>68e07d2d-60c0-4c36-b166-550c87b1502d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>84fdf604-8543-43ab-a94d-cbe998bb1af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Property For</value>
      <webElementGuid>e209c2ce-3b29-4e46-8181-a66fe9441475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>38a70ebf-67ea-40bb-84f1-54f619586d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>839e1f11-2c85-4a57-977a-12fe2e85908d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Buy</value>
      <webElementGuid>93d7e3e0-6c96-44c8-abcd-e9e438b8b041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Buy&quot;)</value>
      <webElementGuid>de243459-c2d5-4bb1-a0c8-ac20033a9af5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Buy']</value>
      <webElementGuid>cfb7043c-439a-4d8a-b17d-b62ccea4966c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[4]/div/div/label/input</value>
      <webElementGuid>3e5c3c0b-5783-42e6-91f6-86bb4d6096a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/label/input</value>
      <webElementGuid>c170fa62-26bc-4978-937a-7b0d91a62816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Buy' and @name = 'Property For' and @type = 'radio']</value>
      <webElementGuid>7922cebd-044f-45f5-bba6-84281ec77b54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
