<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AreaAmpangAmpang HilirBandar Damai P_1ed93d</name>
   <tag></tag>
   <elementGuidId>2b3d9ca9-fc08-43fd-8888-27134a3a61b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9217b297-19ee-4fb0-a78f-dfbd025aa75d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>4a705330-773f-409e-8fcc-96bb9b320473</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>bb37a318-a394-4d3b-b5f4-c39e5db638a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>06cdaa9e-0fe0-4e3b-be91-b69dcdbb04d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAmpangAmpang HilirBandar Damai PerdanaBandar MenjalaraBandar Tasik SelatanBangsarBatu CavesBrickfieldsBukit BintangBukit JalilBukit KiaraBukit LedangBukit Tunku (Kenny Hills)Chan Sow LinCherasCity CentreCountry Heights DamansaraDamansaraDamansara HeightsDesa PandanDesa Park CityDesa PetalingDutamasFederal HillJalan IpohJalan Klang LamaJalan KuchingJalan Sultan IsmailJinjangKampung Kerinchi (Bangsar South)KepongKeramatKL CityKL Eco CityKL SentralKLCCKuchai LamaMid Valley CityMont KiaraOUGPandan IndahPandan JayaPandan PerdanaPantaiPuchongSalak SelatanSegambutSentulSeputehSetapakSetiawangsaSri HartamasSri PetalingSungai BesiSungai PenchalaSunway SPKTaman DesaTaman DutaTaman MelawatiTaman Tun Dr IsmailTitiwangsaWangsa Maju</value>
      <webElementGuid>b79bc0fb-5bd1-4a5d-9fdd-c5533fca408e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>df098b51-1f19-4eb6-bee5-d4b0d9668237</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Area']</value>
      <webElementGuid>d90ffec6-56c4-4f96-9b97-276b3cd5d290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[16]/div[5]/div[3]/select</value>
      <webElementGuid>6a3d5de6-9839-4131-a4a4-343b051ab734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[14]/following::select[1]</value>
      <webElementGuid>c22c5ec1-8050-4c63-85f0-c7b893ad3b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coordinate :'])[1]/preceding::select[1]</value>
      <webElementGuid>bb960a62-6a69-4df6-b059-aa7f39debda0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='auto refresh/generated when saved'])[1]/preceding::select[1]</value>
      <webElementGuid>472abb27-3b1b-4753-8c37-bba5eb1861cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[3]/select</value>
      <webElementGuid>05f76bbe-2d50-4c77-9477-8b5ea16b318d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Area' and @name = 'Area' and (text() = 'AreaAmpangAmpang HilirBandar Damai PerdanaBandar MenjalaraBandar Tasik SelatanBangsarBatu CavesBrickfieldsBukit BintangBukit JalilBukit KiaraBukit LedangBukit Tunku (Kenny Hills)Chan Sow LinCherasCity CentreCountry Heights DamansaraDamansaraDamansara HeightsDesa PandanDesa Park CityDesa PetalingDutamasFederal HillJalan IpohJalan Klang LamaJalan KuchingJalan Sultan IsmailJinjangKampung Kerinchi (Bangsar South)KepongKeramatKL CityKL Eco CityKL SentralKLCCKuchai LamaMid Valley CityMont KiaraOUGPandan IndahPandan JayaPandan PerdanaPantaiPuchongSalak SelatanSegambutSentulSeputehSetapakSetiawangsaSri HartamasSri PetalingSungai BesiSungai PenchalaSunway SPKTaman DesaTaman DutaTaman MelawatiTaman Tun Dr IsmailTitiwangsaWangsa Maju' or . = 'AreaAmpangAmpang HilirBandar Damai PerdanaBandar MenjalaraBandar Tasik SelatanBangsarBatu CavesBrickfieldsBukit BintangBukit JalilBukit KiaraBukit LedangBukit Tunku (Kenny Hills)Chan Sow LinCherasCity CentreCountry Heights DamansaraDamansaraDamansara HeightsDesa PandanDesa Park CityDesa PetalingDutamasFederal HillJalan IpohJalan Klang LamaJalan KuchingJalan Sultan IsmailJinjangKampung Kerinchi (Bangsar South)KepongKeramatKL CityKL Eco CityKL SentralKLCCKuchai LamaMid Valley CityMont KiaraOUGPandan IndahPandan JayaPandan PerdanaPantaiPuchongSalak SelatanSegambutSentulSeputehSetapakSetiawangsaSri HartamasSri PetalingSungai BesiSungai PenchalaSunway SPKTaman DesaTaman DutaTaman MelawatiTaman Tun Dr IsmailTitiwangsaWangsa Maju')]</value>
      <webElementGuid>901d173f-b90e-45a2-a34f-0835ed284934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
