<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TenureFreeholdLease TenancyLeasehold_6238e3</name>
   <tag></tag>
   <elementGuidId>d2787f10-250b-4c10-8d64-3eb2be876adb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Tenure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Tenure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f9a9f90c-4230-48b1-8fc3-f6fb38050a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Tenure</value>
      <webElementGuid>6fe8e341-20b5-45b1-aa16-e957191029e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Tenure</value>
      <webElementGuid>a4e14bc6-6ca3-48ba-81b3-42acad15374e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>540ee0ca-a63f-439f-aba8-d53a098f9adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TenureFreeholdLease TenancyLeaseholdMalay Reserved LandUnknown</value>
      <webElementGuid>417a4093-ac0d-474a-af6a-0e2808b36659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Tenure&quot;)</value>
      <webElementGuid>03a76f30-b8b3-4455-ba4d-79446c67fbb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Tenure']</value>
      <webElementGuid>80c909c5-1624-4bb9-8c53-0bde84749ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[21]/div[2]/select</value>
      <webElementGuid>42f2748a-13f2-464e-8920-23361246e6e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[18]/following::select[1]</value>
      <webElementGuid>3924cb52-c73c-453a-9c8e-4394d69d4207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title Type :'])[1]/preceding::select[1]</value>
      <webElementGuid>b64df7e8-e09f-4ecf-b905-c1d8f93caa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[21]/div[2]/select</value>
      <webElementGuid>865c39ba-1c15-4aa8-857d-464bccaf1938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Tenure' and @name = 'Tenure' and (text() = 'TenureFreeholdLease TenancyLeaseholdMalay Reserved LandUnknown' or . = 'TenureFreeholdLease TenancyLeaseholdMalay Reserved LandUnknown')]</value>
      <webElementGuid>84bcb045-13cb-467e-8c44-d6b200d47d80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
