<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Subsale_Property Listing</name>
   <tag></tag>
   <elementGuidId>205fb113-bebc-476e-a0b9-bb88e8bcab29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Subsale</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>845e03b5-7456-470b-9118-3f1bc12eb0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Subsale</value>
      <webElementGuid>598af9cd-56fa-4b63-aff9-0cab4e084e78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Property Listing</value>
      <webElementGuid>03ebe175-4eae-4887-915c-402967ccd213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7f6b993d-69e8-45e7-982a-a7e9e3cf9d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>547f2a3b-4697-479e-a8f5-a6998a4f67f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Subsale</value>
      <webElementGuid>9f11a43c-60b9-41d6-825a-8c794e36417f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Subsale&quot;)</value>
      <webElementGuid>05a2d648-e87b-4c8d-b467-0fbbd1b0ef45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Subsale']</value>
      <webElementGuid>aeb3581b-a6c8-4d5d-b332-f4e850fe6c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[3]/div/div/label/input</value>
      <webElementGuid>8bdc8f3e-3802-44cb-8e27-941d4a284b26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/label/input</value>
      <webElementGuid>13d2ff17-cdbf-4a53-b965-4dc24d67c2d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Subsale' and @name = 'Property Listing' and @type = 'radio']</value>
      <webElementGuid>45dcfddd-faf2-49be-a9a5-cdb5840da0ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
