<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rent_Property For</name>
   <tag></tag>
   <elementGuidId>a325b4ad-0cbd-4571-9d25-7b8ea320c57f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Rent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Rent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e499e76a-640a-41d4-ab81-7535fe5567ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Rent</value>
      <webElementGuid>aaa235ce-9664-4a55-80bb-1c5f2b011d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Property For</value>
      <webElementGuid>28fe71cc-7625-475c-8f8b-b43b1dc8ee79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>65ff6a7f-ad8d-4947-bbf9-4c4ae2f8caf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>664abc1d-822d-4ba7-a3e2-c4df368b8f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Rent</value>
      <webElementGuid>a10c32b0-11f8-4056-9af3-dc905908ee59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Rent&quot;)</value>
      <webElementGuid>3f633299-a0d8-444f-95b2-f14c60e64f9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Rent']</value>
      <webElementGuid>afb5d254-1c41-4f1e-9646-3fcee70fefa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[4]/div[2]/div/label/input</value>
      <webElementGuid>ebcbec2f-f954-4e6e-8e55-2412de7eaff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/label/input</value>
      <webElementGuid>84942525-ce65-46e4-b8b0-40f6fe8fb82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Rent' and @name = 'Property For' and @type = 'radio']</value>
      <webElementGuid>ce044ca7-cce4-4bf1-8875-8241e3a5dac5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
