<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Commercial_Listing Category</name>
   <tag></tag>
   <elementGuidId>4c8d95d5-5f84-4cee-a65b-8fcbd0958fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Commercial</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Commercial']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afdb421f-6a60-4659-95fb-45d4d30ae97e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>ff1f0365-4d58-4ef6-bc23-8bd3c1125160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Listing Category</value>
      <webElementGuid>88cc67bf-3fdd-4403-905b-a479719ea6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>af51f32f-9d6b-4974-9b03-6035fb396c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>69046acc-ff52-4b72-a0b7-5a568fb1068d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Commercial</value>
      <webElementGuid>232c96b4-590e-499f-8097-9b08b6519882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Commercial&quot;)</value>
      <webElementGuid>49c3177d-a201-4182-b0ad-f79d105b9ffc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Commercial']</value>
      <webElementGuid>61ebf92b-47e7-4ce2-9d25-05483ca41772</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[5]/div/div/label/input</value>
      <webElementGuid>f5c04465-57bb-4698-9d2f-cd7f155a36f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/label/input</value>
      <webElementGuid>2da1c0a7-8c8f-4dfb-9b0f-0bc95c21f35f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Commercial' and @name = 'Listing Category' and @type = 'radio']</value>
      <webElementGuid>dd1947e4-7e82-4742-a035-938bc787d191</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
