<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OccupancyOwner OccupiedTenantedUnkno_9c6ff9</name>
   <tag></tag>
   <elementGuidId>7f098da8-9f01-4c9e-8a50-d0d49b4e2491</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Occupancy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Occupancy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2caea4d3-2b06-4c0e-8035-f1985787f119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Occupancy</value>
      <webElementGuid>09623add-36a8-41fb-8358-85bc02f3a573</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Occupancy</value>
      <webElementGuid>74d6a14d-1d50-4ba5-ae61-199c956e6b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>156e1a65-7f28-409d-8bcb-ecaf8caf027a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OccupancyOwner OccupiedTenantedUnknownVacant</value>
      <webElementGuid>f31ab153-e8cc-47be-abc1-125bd1ce5144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Occupancy&quot;)</value>
      <webElementGuid>85b31a46-d9f6-4e44-932f-6ce8370904eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Occupancy']</value>
      <webElementGuid>b9dfaf97-4bbe-4eb3-ba29-668849ab1660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[17]/div[2]/select</value>
      <webElementGuid>dfd11076-8eb1-425a-b0ce-f73365d2e784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occupancy :'])[1]/following::select[1]</value>
      <webElementGuid>f7233b01-bee6-44e4-8411-277c906cd8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direction :'])[1]/following::select[2]</value>
      <webElementGuid>e760d78d-77cf-4c79-867e-e3f65fc98ee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit Type :'])[1]/preceding::select[1]</value>
      <webElementGuid>23b5d3d9-1865-4b82-816d-957b2235f11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Furnishing :'])[1]/preceding::select[2]</value>
      <webElementGuid>55511c6c-1c16-4c59-8183-ee93eea0b00e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div[2]/select</value>
      <webElementGuid>54f8847e-5632-42c9-a01a-24da71397409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Occupancy' and @name = 'Occupancy' and (text() = 'OccupancyOwner OccupiedTenantedUnknownVacant' or . = 'OccupancyOwner OccupiedTenantedUnknownVacant')]</value>
      <webElementGuid>0205eb05-2b4f-4593-a3e6-9e4ddd52461d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
