<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AreaAyer BaloiAyer HitamBatu AnamBat_dda1d0</name>
   <tag></tag>
   <elementGuidId>50ed0368-003b-4440-9f28-47c4c3bed721</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Area</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Area']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>da23caa6-c874-4912-9540-f7e5a6eaf6f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>1ec052e7-8a29-4f1f-9c34-dc88177f3e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Area</value>
      <webElementGuid>5686e49f-e593-43ad-903f-343490d1efbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>85e2b085-09fe-4a9c-8ebd-331f34247c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AreaAyer BaloiAyer HitamBatu AnamBatu PahatBekokBenutBukit GambirBukit PasirBukit SerampangChaahEndauGelang PatahGerisekGugusan Taib AndakHorizon HillsIskandar Puteri (Nusajaya)JementahJohor BahruKahangKampung Kenangan Tun Dr IsmailKluangKota TinggiKukupKulaiLabisLayang-LayangMasaiMediniMersingMuarPagohPalohPanchorParit JawaParit RajaParit SulongPasir GudangPekan NenasPengerangPerlingPermas JayaPlentongPontianPuteri HarbourRengamRengitSegamatSemerahSenaiSenggarangSenibongSeri GadangSetia IndahSetia TropikaSimpang RengamSkudaiSungai MatiTampoiTangkakTebrauUlu TiramYong Peng</value>
      <webElementGuid>eaf81494-b919-4f80-9af4-8b7666981ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Area&quot;)</value>
      <webElementGuid>7ea55779-54d5-48b7-801a-f4e051a37eb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Area']</value>
      <webElementGuid>0ed9aeda-6c20-4396-b9a1-2e4a4086f6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/main/div/div/div[2]/div/div[2]/div[10]/div[6]/div[2]/select</value>
      <webElementGuid>7f732b3b-692f-4083-b88d-f087f6ccebf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>11aea2c6-b1bd-46cf-9d23-9cf9057f0bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coordinate :'])[1]/preceding::select[1]</value>
      <webElementGuid>7c93388d-5363-43f0-b0f2-ded4b01d2fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='auto refresh/generated when saved'])[1]/preceding::select[1]</value>
      <webElementGuid>70100a6b-7fd6-4349-a56a-1da25d6c1c92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[6]/div[2]/select</value>
      <webElementGuid>b5fee2bc-5eaf-47c3-9b4b-572702c34699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Area' and @name = 'Area' and (text() = 'AreaAyer BaloiAyer HitamBatu AnamBatu PahatBekokBenutBukit GambirBukit PasirBukit SerampangChaahEndauGelang PatahGerisekGugusan Taib AndakHorizon HillsIskandar Puteri (Nusajaya)JementahJohor BahruKahangKampung Kenangan Tun Dr IsmailKluangKota TinggiKukupKulaiLabisLayang-LayangMasaiMediniMersingMuarPagohPalohPanchorParit JawaParit RajaParit SulongPasir GudangPekan NenasPengerangPerlingPermas JayaPlentongPontianPuteri HarbourRengamRengitSegamatSemerahSenaiSenggarangSenibongSeri GadangSetia IndahSetia TropikaSimpang RengamSkudaiSungai MatiTampoiTangkakTebrauUlu TiramYong Peng' or . = 'AreaAyer BaloiAyer HitamBatu AnamBatu PahatBekokBenutBukit GambirBukit PasirBukit SerampangChaahEndauGelang PatahGerisekGugusan Taib AndakHorizon HillsIskandar Puteri (Nusajaya)JementahJohor BahruKahangKampung Kenangan Tun Dr IsmailKluangKota TinggiKukupKulaiLabisLayang-LayangMasaiMediniMersingMuarPagohPalohPanchorParit JawaParit RajaParit SulongPasir GudangPekan NenasPengerangPerlingPermas JayaPlentongPontianPuteri HarbourRengamRengitSegamatSemerahSenaiSenggarangSenibongSeri GadangSetia IndahSetia TropikaSimpang RengamSkudaiSungai MatiTampoiTangkakTebrauUlu TiramYong Peng')]</value>
      <webElementGuid>4cbf5a56-498a-4f68-a0c2-4b20f9b970a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
